// SDG Region mapping based on UN Statistical Division
const regionMapping = {
  // Australia and New Zealand
  'australia': 'Australia and New Zealand',
  'new zealand': 'Australia and New Zealand',

  // Central and Southern Asia
  'afghanistan': 'Central and Southern Asia',
  'bangladesh': 'Central and Southern Asia',
  'bhutan': 'Central and Southern Asia',
  'india': 'Central and Southern Asia',
  'iran': 'Central and Southern Asia',
  'kazakhstan': 'Central and Southern Asia',
  'kyrgyzstan': 'Central and Southern Asia',
  'maldives': 'Central and Southern Asia',
  'nepal': 'Central and Southern Asia',
  'pakistan': 'Central and Southern Asia',
  'sri lanka': 'Central and Southern Asia',
  'tajikistan': 'Central and Southern Asia',
  'turkmenistan': 'Central and Southern Asia',
  'uzbekistan': 'Central and Southern Asia',

  // Eastern and South-Eastern Asia
  'brunei': 'Eastern and South-Eastern Asia',
  'cambodia': 'Eastern and South-Eastern Asia',
  'china': 'Eastern and South-Eastern Asia',
  'indonesia': 'Eastern and South-Eastern Asia',
  'japan': 'Eastern and South-Eastern Asia',
  'laos': 'Eastern and South-Eastern Asia',
  'malaysia': 'Eastern and South-Eastern Asia',
  'mongolia': 'Eastern and South-Eastern Asia',
  'myanmar': 'Eastern and South-Eastern Asia',
  'north korea': 'Eastern and South-Eastern Asia',
  'philippines': 'Eastern and South-Eastern Asia',
  'singapore': 'Eastern and South-Eastern Asia',
  'south korea': 'Eastern and South-Eastern Asia',
  'thailand': 'Eastern and South-Eastern Asia',
  'timor-leste': 'Eastern and South-Eastern Asia',
  'vietnam': 'Eastern and South-Eastern Asia',

  // Europe and North America
  'albania': 'Europe and North America',
  'andorra': 'Europe and North America',
  'austria': 'Europe and North America',
  'belarus': 'Europe and North America',
  'belgium': 'Europe and North America',
  'bosnia and herzegovina': 'Europe and North America',
  'bulgaria': 'Europe and North America',
  'canada': 'Europe and North America',
  'croatia': 'Europe and North America',
  'czech republic': 'Europe and North America',
  'denmark': 'Europe and North America',
  'estonia': 'Europe and North America',
  'finland': 'Europe and North America',
  'france': 'Europe and North America',
  'germany': 'Europe and North America',
  'greece': 'Europe and North America',
  'hungary': 'Europe and North America',
  'iceland': 'Europe and North America',
  'ireland': 'Europe and North America',
  'italy': 'Europe and North America',
  'latvia': 'Europe and North America',
  'liechtenstein': 'Europe and North America',
  'lithuania': 'Europe and North America',
  'luxembourg': 'Europe and North America',
  'malta': 'Europe and North America',
  'moldova': 'Europe and North America',
  'monaco': 'Europe and North America',
  'montenegro': 'Europe and North America',
  'netherlands': 'Europe and North America',
  'north macedonia': 'Europe and North America',
  'norway': 'Europe and North America',
  'poland': 'Europe and North America',
  'portugal': 'Europe and North America',
  'romania': 'Europe and North America',
  'russia': 'Europe and North America',
  'san marino': 'Europe and North America',
  'serbia': 'Europe and North America',
  'slovakia': 'Europe and North America',
  'slovenia': 'Europe and North America',
  'spain': 'Europe and North America',
  'sweden': 'Europe and North America',
  'switzerland': 'Europe and North America',
  'ukraine': 'Europe and North America',
  'united kingdom': 'Europe and North America',
  'united states': 'Europe and North America',
  'vatican': 'Europe and North America',

  // Latin America and the Caribbean
  'antigua and barbuda': 'Latin America and the Caribbean',
  'argentina': 'Latin America and the Caribbean',
  'bahamas': 'Latin America and the Caribbean',
  'barbados': 'Latin America and the Caribbean',
  'belize': 'Latin America and the Caribbean',
  'bolivia': 'Latin America and the Caribbean',
  'brazil': 'Latin America and the Caribbean',
  'chile': 'Latin America and the Caribbean',
  'colombia': 'Latin America and the Caribbean',
  'costa rica': 'Latin America and the Caribbean',
  'cuba': 'Latin America and the Caribbean',
  'dominica': 'Latin America and the Caribbean',
  'dominican republic': 'Latin America and the Caribbean',
  'ecuador': 'Latin America and the Caribbean',
  'el salvador': 'Latin America and the Caribbean',
  'grenada': 'Latin America and the Caribbean',
  'guatemala': 'Latin America and the Caribbean',
  'guyana': 'Latin America and the Caribbean',
  'haiti': 'Latin America and the Caribbean',
  'honduras': 'Latin America and the Caribbean',
  'jamaica': 'Latin America and the Caribbean',
  'mexico': 'Latin America and the Caribbean',
  'nicaragua': 'Latin America and the Caribbean',
  'panama': 'Latin America and the Caribbean',
  'paraguay': 'Latin America and the Caribbean',
  'peru': 'Latin America and the Caribbean',
  'saint kitts and nevis': 'Latin America and the Caribbean',
  'saint lucia': 'Latin America and the Caribbean',
  'saint vincent and the grenadines': 'Latin America and the Caribbean',
  'suriname': 'Latin America and the Caribbean',
  'trinidad and tobago': 'Latin America and the Caribbean',
  'uruguay': 'Latin America and the Caribbean',
  'venezuela': 'Latin America and the Caribbean',

  // Northern Africa and Western Asia
  'algeria': 'Northern Africa and Western Asia',
  'armenia': 'Northern Africa and Western Asia',
  'azerbaijan': 'Northern Africa and Western Asia',
  'bahrain': 'Northern Africa and Western Asia',
  'cyprus': 'Northern Africa and Western Asia',
  'egypt': 'Northern Africa and Western Asia',
  'georgia': 'Northern Africa and Western Asia',
  'iraq': 'Northern Africa and Western Asia',
  'israel': 'Northern Africa and Western Asia',
  'jordan': 'Northern Africa and Western Asia',
  'kuwait': 'Northern Africa and Western Asia',
  'lebanon': 'Northern Africa and Western Asia',
  'libya': 'Northern Africa and Western Asia',
  'morocco': 'Northern Africa and Western Asia',
  'oman': 'Northern Africa and Western Asia',
  'palestine': 'Northern Africa and Western Asia',
  'qatar': 'Northern Africa and Western Asia',
  'saudi arabia': 'Northern Africa and Western Asia',
  'sudan': 'Northern Africa and Western Asia',
  'syria': 'Northern Africa and Western Asia',
  'tunisia': 'Northern Africa and Western Asia',
  'turkey': 'Northern Africa and Western Asia',
  'united arab emirates': 'Northern Africa and Western Asia',
  'yemen': 'Northern Africa and Western Asia',

  // Oceania (excluding Australia and New Zealand)
  'fiji': 'Oceania',
  'kiribati': 'Oceania',
  'marshall islands': 'Oceania',
  'micronesia': 'Oceania',
  'nauru': 'Oceania',
  'palau': 'Oceania',
  'papua new guinea': 'Oceania',
  'samoa': 'Oceania',
  'solomon islands': 'Oceania',
  'tonga': 'Oceania',
  'tuvalu': 'Oceania',
  'vanuatu': 'Oceania',

  // Sub-Saharan Africa
  'angola': 'Sub-Saharan Africa',
  'benin': 'Sub-Saharan Africa',
  'botswana': 'Sub-Saharan Africa',
  'burkina faso': 'Sub-Saharan Africa',
  'burundi': 'Sub-Saharan Africa',
  'cameroon': 'Sub-Saharan Africa',
  'cape verde': 'Sub-Saharan Africa',
  'central african republic': 'Sub-Saharan Africa',
  'chad': 'Sub-Saharan Africa',
  'comoros': 'Sub-Saharan Africa',
  'congo': 'Sub-Saharan Africa',
  'democratic republic of congo': 'Sub-Saharan Africa',
  'djibouti': 'Sub-Saharan Africa',
  'equatorial guinea': 'Sub-Saharan Africa',
  'eritrea': 'Sub-Saharan Africa',
  'eswatini': 'Sub-Saharan Africa',
  'ethiopia': 'Sub-Saharan Africa',
  'gabon': 'Sub-Saharan Africa',
  'gambia': 'Sub-Saharan Africa',
  'ghana': 'Sub-Saharan Africa',
  'guinea': 'Sub-Saharan Africa',
  'guinea-bissau': 'Sub-Saharan Africa',
  'ivory coast': 'Sub-Saharan Africa',
  'kenya': 'Sub-Saharan Africa',
  'lesotho': 'Sub-Saharan Africa',
  'liberia': 'Sub-Saharan Africa',
  'madagascar': 'Sub-Saharan Africa',
  'malawi': 'Sub-Saharan Africa',
  'mali': 'Sub-Saharan Africa',
  'mauritania': 'Sub-Saharan Africa',
  'mauritius': 'Sub-Saharan Africa',
  'mozambique': 'Sub-Saharan Africa',
  'namibia': 'Sub-Saharan Africa',
  'niger': 'Sub-Saharan Africa',
  'nigeria': 'Sub-Saharan Africa',
  'rwanda': 'Sub-Saharan Africa',
  'sao tome and principe': 'Sub-Saharan Africa',
  'senegal': 'Sub-Saharan Africa',
  'seychelles': 'Sub-Saharan Africa',
  'sierra leone': 'Sub-Saharan Africa',
  'somalia': 'Sub-Saharan Africa',
  'south africa': 'Sub-Saharan Africa',
  'south sudan': 'Sub-Saharan Africa',
  'tanzania': 'Sub-Saharan Africa',
  'togo': 'Sub-Saharan Africa',
  'uganda': 'Sub-Saharan Africa',
  'zambia': 'Sub-Saharan Africa',
  'zimbabwe': 'Sub-Saharan Africa'
};

export const getSDGRegion = (countryName) => {
  if (!countryName) return 'Unknown';
  
  const normalizedCountry = countryName.toLowerCase().trim();
  return regionMapping[normalizedCountry] || 'Unknown';
};

export const getAllSDGRegions = () => {
  return [
    'Australia and New Zealand',
    'Central and Southern Asia',
    'Eastern and South-Eastern Asia',
    'Europe and North America',
    'Latin America and the Caribbean',
    'Northern Africa and Western Asia',
    'Oceania',
    'Sub-Saharan Africa'
  ];
};